In [2]:
import numpy as np

identity_matrix = np.identity(5)
display(identity_matrix)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

5*5 identity matrix


In [5]:
import numpy as np
marks = np.random.randint(0, 101, size=(10, 3))
display(marks)
average_marks_per_student = np.mean(marks, axis=1)
display(average_marks_per_student)

array([[19, 44,  7],
       [ 8,  8, 25],
       [28, 50, 24],
       [29, 28, 59],
       [84, 73, 92],
       [27, 38, 54],
       [71, 54, 18],
       [ 3, 86, 60],
       [ 3,  0, 24],
       [ 5, 99, 69]])

array([23.33333333, 13.66666667, 34.        , 38.66666667, 83.        ,
       39.66666667, 47.66666667, 49.66666667,  9.        , 57.66666667])

average

In [13]:
list = [10,20,30,40,50]
result = list[1:4]
print(result)

[20, 30, 40]


slicing


In [14]:
arr = np.arange(12)
reshaped = arr.reshape(3, 4)
flattened = reshaped.flatten()

print(reshaped)
print(flattened)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


reshape and flatten back


In [20]:
import numpy as np

marks = np.array([50, 60, 70, 80])
print(marks + 10)


[60 70 80 90]
