In [1]:
import regex as re
import pandas as pd
import numpy as np



text = "hello 123 world 890"

match_result = re.match(r"\d+", text)
search_result = re.search(r"\d+", text)
findall_result = re.findall(r"\d+", text)

print(match_result)
print(search_result.group())
print(findall_result)


#numpy
a = np.array([1,2,3,4,5])
print(a)

b = np.arange(1,10,2)
print(b)

c = np.linspace(0,10,5)
print(c)

d = np.full((3,2),0)
print(d)

e = np.ones((2,4))
print(e)

f = np.zeros((2,4))
print(f)

#stats

data = np.array([1,2,2,3,3,4,5,5])
print(data)

mean = np.mean(data)
print(mean)

median = np.median(data)
print(median)

None
123
['123', '890']
[1 2 3 4 5]
[1 3 5 7 9]
[ 0.   2.5  5.   7.5 10. ]
[[0 0]
 [0 0]
 [0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1 2 2 3 3 4 5 5]
3.125
3.0
